# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1db7084687e34ab0851559f6b79a65da36853eb9383b6e7c07fbca485bcf189d703c590ca242ed24638a5d03006dcba633f0a41bcadffd90fb17fef10bc1aa

test:
  secret_key_base: 80999204cb1f04528f23dd31841e385e95a74538bbe528b006c5baee3fb31d8a484aab37d76b15284401f796ebef4ce9b91beb93add21d42a1e97d9396c9eef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
